title: tcloud's Personal Blog
author:
  name: tcloud

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  A place to put my personal thoughts about tech and occasionally other stuff.

# use GitHub Markdown
markdown: GFM
highlighter: rouge

# theme selector
remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings

# If you want to link only specific pages in your header, use this and add the path to the pages
# in order as they should show up.
header_pages:
  - repositories/index.md
  - about/index.md

# Minima specific settings for v3.0+
minima:
  skin: auto
  
  # Minima date format
  # Doc: https://shopify.github.io/liquid/filters/date/
  date_format: "%Y-%m-%d"

  # Show excerpts on the homepage
  show_excerpts: true

  # Generate social links in footer
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/t-c-l-o-u-d"
