# GNU Affero General Public License v3.0 or later (see COPYING or https://www.gnu.org/licenses/agpl.txt)

FROM ghcr.io/t-c-l-o-u-d/devcontainer-base-images/arch-linux-devcontainer:latest

# pull in USER from devcontainer.json
ARG USER

# add the USER to the image
RUN useradd --create-home --shell /usr/bin/bash --groups wheel ${USER}

# install jekyll dependencies
RUN pacman --sync --refresh --noconfirm --needed \
    ruby \
    ruby-stdlib \
    rubygems \
    zlib-ng

# switch to USER
USER ${USER}

# install jekyll
RUN export GEM_HOME="$(gem env user_gemhome)"; gem install jekyll bundler

# install site
COPY Gemfile /tmp/
RUN export GEM_HOME="$(gem env user_gemhome)"; ${GEM_HOME}/bin/bundle install --gemfile=/tmp/Gemfile

# add bash files
RUN mkdir --parents "${HOME}/.config/bash/"
COPY .devcontainer/devcontainer-blog /home/${USER}/.config/bash/devcontainer-blog
