#!/usr/bin/bash
# GNU Affero General Public License v3.0 or later (see COPYING or https://www.gnu.org/licenses/agpl.txt)

# setup location for gems
export GEM_HOME="${HOME}/gems"

# setup location for gem binaries
_append_path "${GEM_HOME}/bin"

alias srv='bundle exec jekyll serve --livereload --open-url http://localhost:4000/'
